### ISSUE TITLE
Shop

### ISSUE THREAD

**Issue by nklbigone** [nklbigone/cdp_test#2]
## Evaluation Items

- [x] Include the Ownable module in all classes that require owner privileges.
- [x] Ensure that the purchase amount of all items in the cart is transferred from the cart owner's wallet to the item owner's wallet.
- [x] The owner rights of all items in the cart are transferred to the cart owner.
- [x] The contents of the cart should be empty.

**Comment by PeterYves** [comment]
Congratulations Alexis ..You passed.

✅ Include the Ownable module in all classes that require owner privileges.
✅ Ensure that the purchase amount of all items in the cart is transferred from the cart owner's wallet to the item owner's wallet.
✅The owner rights of all items in the cart are transferred to the cart owner.
✅ The contents of the cart should be empty.
