### ISSUE TITLE
Program to display the amount

### ISSUE THREAD

**Issue by nklbigone** [nklbigone/cdp_test#6]
# Evaluation Items

- [x] The design and images must appear the same as the example page.
- [x] Products can be added.
- [x] When adding a product, the product name, amount, and quantity should be displayed in a pop-up window.
- [x] When the total amount is displayed, the product name, amount, quantity, subtotal, shipping cost, and total amount of the added product should be displayed correctly.
- [x] The shipping cost should be 500 yen if the total amount is less than 2000 yen, 250 yen if the total amount is 2000 yen or more, and 0 yen if the total amount is 3000 yen or more.

**Comment by PeterYves** [comment]
@nklbigone Thank you for submitting.

You have passed this task. Please proceed.

✅ The design and images must appear the same as the example page.
✅ Products can be added.
✅ When adding a product, the product name, amount, and quantity should be displayed in a pop-up window.
✅ When the total amount is displayed, the product name, amount, quantity, subtotal, shipping cost, and total amount of the added product should be displayed correctly.
✅ The shipping cost should be 500 yen if the total amount is less than 2000 yen, 250 yen if the total amount is 2000 yen or more, and 0 yen if the total amount is 3000 yen or more.
